Remove non-ascii character from README.rst
The python packaging doesn't declare itself to prefer utf-8, but the README contains it, so the `long_description=open('README.rst').read()` is failing with:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3800: ordinal not in range(128)

There's only this single character, though, so just replace it with ASCII and solve the issue the easy way.